name: Modoo
options:
  bundleIdPrefix: io.interactord.modoo
  deploymentTarget:
    iOS: 13.0
  defaultConfig: Debug
  createIntermediateGroups: true
  transitivelyLinkDependencies: true
  tabWidth: 2
  indentWidth: 2

settings:
  base:
    SWIFT_VERSION: 5.3
    CLANG_ENABLE_MODULES: YES
    COPY_PHASE_STRIP: NO

schemes:
  AllTests:
    build:
      targets:
        Application: test
    test:
      gatherCoverageData: true
      targets:
        - ApplicationTests

include:
  - packages.yml
  - Projects/workspace.yml
  - Projects/Application/project.yml
