targets:
  Base:
    type: framework
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - sdk: Foundation.framework
    settings:
      PRODUCT_NAME: Base
      PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_NAME)
      INFOPLIST_FILE: $(SRCROOT)/Projects/Info.plist
    scheme:
      testTargets:
        - BaseTests
      gatherCoverageData: true

  BaseTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Base
      - target: Testing
    settings:
      WRAPPER_EXTENSION: xctest
      PRODUCT_NAME: ${target_name}
      PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_NAME)
      BUNDLE_LOADER: $(TEST_HOST)
      INFOPLIST_FILE: $(SRCROOT)/Projects/Info.plist
    profile:
      config: Debug
