name: CI

on:
  push:
    branches: [ feature-*, master ]
  pull_request: 
    branches: [ master, feature ]

jobs:
  test:
    runs-on: macOS-latest 
    env:
      WORKSPACE: Modoo.xcworkspace
      PROJECT: Modoo.xcodeproj
      SCHEME: AllTests
      CODECOV_PACKAGE_NAME: Modoo
      SDK: iphonesimulator
      DESTINATION: platform=iOS Simulator,name=iPhone 11 Pro,OS=latest
      SLATER_REPORT_PATH: build/coverage/cobertura.xml
  
    steps:
    - uses: actions/checkout@v1

    - name: Install brewfile
      run: brew bundle --file=./Brewfile
    
    - name: Install Gemfile
      run: bundle install

    - name: Generate Xcode Project
      run: make project
    
    - name: Build and Test with Xcode
      run: |
        set -o pipefail && xcodebuild clean build test \
          -workspace "$WORKSPACE" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`

    - name: Create Code coverage report
      run: |
        slather coverage \
          --scheme "$SCHEME" \
          --cobertura-xml \
          --output-directory build/coverage -i '../*' \
          --workspace "$WORKSPACE" "$PROJECT"
    
    - name: Update Code coverage
      run: |
        bash <(curl -s https://codecov.io/bash) \
          -f "$SLATER_REPORT_PATH" \
          -X coveragepy \
          -X gcov \
          -X xcode \
          -t "$CODECOV_TOKEN"
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}